# Generated by Django 6.0.2 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_testimonial_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
        migrations.AddField(
            model_name="program",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="programs/"),
        ),
        migrations.AddField(
            model_name="project",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
    ]
