# Generated by Django 6.0.2 on 2026-02-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers/'),
        ),
    ]
