# Generated by Django 6.0.2 on 2026-02-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoverviewvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event-overview/'),
        ),
        migrations.AddField(
            model_name='eventoverviewvideo',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
